name: Code Scanning

on:
  push:
  
jobs:
  code-scanning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: CodeQL Analysis
        uses: github/codeql-action/analyze@v1
        with:
          sarif-file: codeql.sarif
          
      - name: Create issue for code scanning alerts
        if: ${{ contains(steps.codeql.outputs.alerts, 'ALERT') }}
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Code scanning alerts found
          body: |
            Code scanning alerts were found in your code. Please review the attached report and take appropriate action.
          labels: vulnerability
          assignees: Cyrof
          projects: |
            {
              "name" : "Pi Website tasks",
              "column_name" : "Vulnerability"
            }
          files: |
            codeql.sarif
        env:
            GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
